// Pay & request: the list of what you are asked to pay, paying a request, declining it, and what
// the other person sees.
import { expect, test } from '@playwright/test'
import { anaAndMarko, expectBalance, expectCleanVisibleCopy, slot } from './helpers'

test.describe('Pay & request on the stage', () => {
  test.use({ viewport: { width: 1280, height: 720 } })

  test('Home counts the Lunch request; the list shows it with the rows below', async ({ page }) => {
    await anaAndMarko(page)
    const ana = slot(page, 'left')
    await expect(ana.locator('[data-tile="payRequest"]')).toContainText('1 to pay')
    await expect(ana.locator('[data-tile="payRequest"]')).toContainText(/^.*1.*$/s)
    await ana.locator('[data-tile="payRequest"]').click()
    const hub = ana.locator('[data-screen="c.payRequest.hub"]')
    await expect(hub).toBeVisible()
    const row = ana.getByTestId('pay-item-r_seed_lunch')
    await expect(row).toContainText('@marko · Lunch')
    await expect(row).toContainText('Request · today 11:52')
    await expect(row).toContainText('13.20')
    await expect(hub.getByTestId('to-pay').locator('h2')).toHaveText('TO PAY')
    await expect(hub.locator('h2')).toHaveText(['TO PAY', 'PAY & REQUEST'])
    await expect(ana.getByTestId('row-send')).toBeVisible()
    // Marko has nothing to pay: no list, and the tile has no count.
    const marko = slot(page, 'right')
    await expect(marko.locator('[data-tile="payRequest"]')).not.toContainText('to pay')
    await expectCleanVisibleCopy(page)
  })

  test('Ana pays the Lunch request: 13.33, Ana 234.17, Marko 146.18, Marko hears of it', async ({ page }) => {
    await anaAndMarko(page)
    const ana = slot(page, 'left')
    const marko = slot(page, 'right')
    await ana.locator('[data-tile="payRequest"]').click()
    await ana.getByTestId('pay-item-r_seed_lunch').click()
    const review = ana.locator('[data-screen="c.payItem.review"]')
    await expect(review).toBeVisible()
    await expect(review.getByRole('heading', { name: 'Pay @marko?' })).toBeVisible()
    await expect(ana.getByTestId('fact-from')).toContainText('@marko · Marko Kovač')
    await expect(ana.getByTestId('fact-fee')).toContainText('0.13 BCPS')
    await expect(ana.getByTestId('fact-fee')).toContainText('≈ €0.12')
    await expect(ana.getByTestId('review-total')).toContainText('13.33 BCPS')
    await expect(ana.getByText('Marko asked today at 11:52.')).toBeVisible()
    await expect(ana.getByRole('button', { name: 'Decline' })).toBeVisible()
    await ana.getByRole('button', { name: 'Pay 13.33' }).dblclick()
    await expect(ana.locator('[data-screen="c.payItem.success"]')).toBeVisible({ timeout: 5000 })
    await expect(ana.getByTestId('success-amount')).toContainText('13.20')
    await expectBalance(page, 'marko', '146.18')
    await expect(marko.getByTestId('banner')).toContainText('@ana paid your request · 13.20 BCPS')
    await ana.getByRole('button', { name: 'Done' }).click()
    await expectBalance(page, 'ana', '234.17')
    // Nothing left to pay.
    await expect(ana.locator('[data-tile="payRequest"]')).not.toContainText('to pay')
    await ana.locator('[data-tile="payRequest"]').click()
    await expect(ana.getByTestId('to-pay')).toHaveCount(0)
  })

  test('Decline asks first; Keep returns to the check; Decline tells Marko and moves nothing', async ({ page }) => {
    await anaAndMarko(page)
    const ana = slot(page, 'left')
    const marko = slot(page, 'right')
    await ana.locator('[data-tile="payRequest"]').click()
    await ana.getByTestId('pay-item-r_seed_lunch').click()
    await ana.getByRole('button', { name: 'Decline' }).click()
    const decline = ana.locator('[data-screen="c.payItem.decline"]')
    await expect(decline).toBeVisible()
    await expect(decline.getByRole('heading', { name: "Decline @marko's request?" })).toBeVisible()
    await expect(decline).toContainText('Marko will see that you declined. No money moves.')
    await expect(decline).toContainText('13.20 BCPS')
    await ana.getByRole('button', { name: 'Keep' }).click()
    await expect(ana.locator('[data-screen="c.payItem.review"]')).toBeVisible()
    await ana.getByRole('button', { name: 'Decline' }).click()
    await ana.getByRole('button', { name: 'Decline', exact: true }).last().click()
    const done = ana.locator('[data-screen="c.payItem.declined"]')
    await expect(done).toBeVisible()
    await expect(done).toContainText('Request declined')
    await expect(marko.getByTestId('banner')).toContainText('@ana declined your request')
    await done.getByRole('button', { name: 'Done' }).click()
    await expectBalance(page, 'ana', '247.50')
    await expectBalance(page, 'marko', '132.98')
    await expect(ana.locator('[data-tile="payRequest"]')).not.toContainText('to pay')
  })
})
