import { z } from 'zod'

// Interface sections of content/copy.en.yaml. Validated at build time together with the engine
// sections (schema.ts); the app imports only the UiCopy type.

const S = z.string().min(1)
const Pillar = z.strictObject({ title: S, body: S })

export const UiCopySchema = z.looseObject({
  app: z.looseObject({ title: S }),
  common: z.strictObject({
    bcps: S,
    deleteKey: S,
    approxEur: S,
    planned: S,
    verified: S,
    verifiedLabel: S,
    close: S,
    done: S,
    cancel: S,
    skip: S,
    edit: S,
    undo: S,
    back: S,
    next: S,
    continue: S,
    toStart: S,
    about: S,
    sending: S,
    balance: S,
    incoming: S,
    rate: S,
    rateChip: S,
    rateInfo: S,
    rateInfoLabel: S,
    phoneLabel: S,
    roleCustomer: S,
    roleBusiness: S,
  }),
  pillars: z.array(Pillar).length(4),
  start: z.strictObject({
    overline: S,
    headline: S,
    lede: S,
    open: S,
    updateReady: S,
    updateApply: S,
  }),
  about: z.strictObject({
    title: S,
    intro: S,
    feesTitle: S,
    fees: z.array(S).min(1),
    privacyTitle: S,
    privacy: S,
    safety: S,
    build: S,
  }),
  notFound: z.strictObject({ title: S, body: S, home: S }),
  fee: z.looseObject({
    chipShort: S,
    chipNone: S,
    chipConversion: S,
    chipCards: S,
    payerYou: S,
    transaction: S,
    paidBy: S,
    paidByYou: S,
    lineYou: S,
    lineOther: S,
    transactionYou: S,
    transactionBy: S,
    feeInfo: S,
    cardInfo: S,
    infoLabel: S,
    cardInfoLabel: S,
  }),
  tape: z.looseObject({ row: S, empty: S, status: z.strictObject({ pending: S, confirmed: S }) }),
  tx: z.strictObject({ to: S, from: S, withNote: S, items: S }),
  errors: z.strictObject({
    insufficientFunds: S,
    unknownRecipient: S,
    selfPayment: S,
    invalidAmount: S,
    maxAmount: S,
    invalidState: S,
    notAllowed: S,
    quoteChanged: S,
    expired: S,
    cancelled: S,
    paid: S,
    sessionFull: S,
    generic: S,
  }),
  nav: z.strictObject({ back: S, home: S, step: S }),
  tiles: z.strictObject({ scan: S, payRequest: S, history: S, charge: S, sales: S, pay: S }),
  hubs: z.strictObject({
    titles: z.strictObject({ payRequest: S, sales: S, pay: S, profile: S, settings: S }),
    rows: z.strictObject({ send: S, allPayments: S, paySupplier: S, notifications: S, about: S, logout: S }),
    sublines: z.strictObject({ sendHint: S, supplierHint: S, salesToday: S }),
  }),
  home: z.strictObject({ profile: S, settings: S, bell: S, bellUnread: S, business: S, tileBadge: S }),
  steps: z.strictObject({
    available: S,
    max: S,
    keypad: S,
    balanceAfter: S,
    arrives: S,
    noteVisibility: S,
    noteField: S,
    backToReview: S,
    total: S,
    fee: S,
    sending: S,
  }),
  party: z.strictObject({ placeholder: S, searchLabel: S, recent: S, business: S, businessIn: S }),
  login: z.strictObject({
    logIn: S,
    biometrics: S,
    chooseAccount: S,
    tapAccount: S,
    otherPhone: S,
    emailLabel: S,
    personal: S,
    business: S,
    continue: S,
    sentTo: S,
    mailChip: S,
    codeTitle: S,
    resendPrompt: S,
    resendAction: S,
    codeBox: S,
    verify: S,
    codeLabel: S,
    emailFilled: S,
    codeFilled: S,
    welcomePerson: S,
    welcomeBusiness: S,
  }),
  logout: z.strictObject({ title: S, body: S, cancel: S, confirm: S }),
  scan: z.strictObject({
    title: S,
    viewfinder: S,
    locked: S,
    lockedLine: S,
    noCode: S,
    hold: S,
    cantScan: S,
    payByUsername: S,
    reviewTitle: S,
    rowTo: S,
    rowItems: S,
    pay: S,
  }),
  charge: z.strictObject({
    title: S,
    table: S,
    items: S,
    custom: S,
    hint: S,
    fromItems: S,
    clear: S,
    charge: S,
    codeTitle: S,
    codeLabel: S,
    valid: S,
    tapToPay: S,
    expired: S,
    newCode: S,
    cancel: S,
    cancelTitle: S,
    cancelBody: S,
    rowAmount: S,
    rowItems: S,
    keep: S,
    cancelCharge: S,
    paid: S,
    received: S,
    quantity: S,
    from: S,
    fromName: S,
    spendable: S,
    fee: S,
    feeValue: S,
    feeShort: S,
    feeShortValue: S,
    reference: S,
    sale: S,
    fromNotification: S,
    newSale: S,
  }),
  paySupplier: z.strictObject({ title: S, toTitle: S, amountTitle: S, noteTitle: S, reviewTitle: S, pay: S }),
  send: z.strictObject({
    title: S,
    toTitle: S,
    amountTitle: S,
    noteTitle: S,
    reviewTitle: S,
    rowTo: S,
    rowAmount: S,
    rowNote: S,
    noNote: S,
    send: S,
  }),
  receipt: z.strictObject({
    paid: S,
    sent: S,
    to: S,
    reference: S,
    fee: S,
    feeLine: S,
    feeLineYou: S,
    time: S,
  }),
  history: z.strictObject({ title: S, pending: S, sale: S }),
  detail: z.strictObject({
    title: S,
    from: S,
    to: S,
    items: S,
    note: S,
    fee: S,
    rate: S,
    status: S,
    reference: S,
    sent: S,
    settled: S,
    settling: S,
    outsideHours: S,
    verified: S,
    verifiedPerson: S,
    verifiedBusiness: S,
    party: S,
    toLine: S,
    fromLine: S,
    feeValue: S,
    paidBy: S,
    paidByYou: S,
    privacyPurchase: S,
    privacyPerson: S,
    sendAgain: S,
    missing: S,
  }),
  profile: z.strictObject({
    identity: S,
    who: S,
    countries: z.strictObject({ SI: S, KR: S }),
  }),
  stage: z.strictObject({
    noOne: S,
    swap: S,
    reset: S,
    fullscreen: S,
    settings: S,
    zoom: S,
    zoomOut: S,
    dateChip: S,
    accountMenu: S,
    toastFor: S,
    toastOpen: S,
    counter: S,
    travelEdge: S,
    handover: S,
  }),
  accountMenu: z.strictObject({
    title: S,
    merchants: S,
    customers: S,
    onThisPhone: S,
    onOtherPhone: S,
    showWelcome: S,
    unread: S,
    close: S,
  }),
  phoneMode: z.strictObject({ pill: S, toast: S, switch: S, upright: S, timeLabel: S, reset: S, settings: S }),
  reset: z.strictObject({ title: S, body: S, option: S, confirm: S, cancel: S, done: S, undo: S, fresh: S }),
  settings: z.strictObject({
    title: S,
    done: S,
    reduceMotion: S,
    sound: S,
    largeText: S,
    tape: S,
    undoReset: S,
    about: S,
    build: S,
  }),
  keys: z.strictObject({ title: S, fullscreen: S, zoom: S, escape: S, help: S, close: S }),
  otherTab: z.strictObject({ title: S, useHere: S }),
  notices: z.strictObject({
    recalculated: S,
    restoreFailed: S,
    storageUnavailable: S,
    writeFailed: S,
    dismiss: S,
  }),
  empty: z.strictObject({ history: S, notifications: z.strictObject({ title: S, body: S }) }),
  notifications: z.strictObject({ title: S, markAll: S, today: S, yesterday: S, earlier: S, unread: S, justNow: S }),
  groups: z.strictObject({ today: S, yesterday: S, thisWeek: S, earlier: S }),
})

export type UiCopy = z.infer<typeof UiCopySchema>
