import {
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowUpRight,
  Bell,
  CalendarClock,
  ChartColumn,
  Circle,
  CreditCard,
  FileLock,
  FilePlus,
  FileText,
  Fingerprint,
  Info,
  Landmark,
  LayoutDashboard,
  Link,
  List,
  LogOut,
  type LucideIcon,
  Map as MapIcon,
  Package,
  Pause,
  Plug,
  Plus,
  QrCode,
  Receipt,
  Repeat,
  ScanLine,
  Send,
  ShoppingBag,
  Split,
  Truck,
  Undo2,
  Users,
  Wallet,
} from 'lucide-react'

// The Lucide icons content/homes.yaml may name (by their kebab-case names). Named imports keep
// the bundle to these; an unknown name shows a plain circle rather than failing.

const ICONS: Record<string, LucideIcon> = {
  'scan-line': ScanLine,
  'arrow-left-right': ArrowLeftRight,
  wallet: Wallet,
  list: List,
  'arrow-up-right': ArrowUpRight,
  'arrow-down-left': ArrowDownLeft,
  link: Link,
  split: Split,
  'shopping-bag': ShoppingBag,
  repeat: Repeat,
  plus: Plus,
  landmark: Landmark,
  'qr-code': QrCode,
  'calendar-clock': CalendarClock,
  'credit-card': CreditCard,
  fingerprint: Fingerprint,
  pause: Pause,
  bell: Bell,
  map: MapIcon,
  info: Info,
  'log-out': LogOut,
  'bar-chart-3': ChartColumn,
  'undo-2': Undo2,
  truck: Truck,
  'file-text': FileText,
  plug: Plug,
  receipt: Receipt,
  'layout-dashboard': LayoutDashboard,
  package: Package,
  users: Users,
  send: Send,
  'file-plus': FilePlus,
  'file-lock': FileLock,
}

export function iconFor(name: string): LucideIcon {
  return ICONS[name] ?? Circle
}
